__asm__(
".global caml_clock_nanosleep\n"
".type caml_clock_nanosleep, @function\n"
"caml_clock_nanosleep:\n"
"    sar     $1, %rdi\n"
"    imul    $1000000, %rdi, %rax\n"
"    push    %r11\n"
"    cqo\n"
"    mov     $1000000000, %rcx\n"
"    div     %rcx\n"
"    push    %rdx\n"   
"    push    %rax\n"
"    mov     $230, %rax\n"
"    mov     $1, %rdi\n"
"    xor     %rsi, %rsi\n"
"    mov     %rsp, %rdx\n"
"    xor     %r10, %r10\n"
"    syscall\n"
"    add     $16, %rsp\n"
"    pop     %r11\n"
"    mov     $1, %rax\n"
"    ret\n"
);