__asm__(
".global caml_long_nanosleep\n"
".type caml_long_nanosleep, @function\n"
"caml_long_nanosleep:\n"
"    sar $1, %rdi\n"
"    imul $1000000, %rdi, %rax\n"
"    push %r11\n"
"    xor %rdx, %rdx\n"
"    mov $1000000000, %rcx\n"
"    div %rcx\n"
"    push %rdx\n"
"    push %rax\n"
"    mov $35, %rax\n"
"    mov %rsp, %rdi\n"
"    xor %rsi, %rsi\n"
"    syscall\n"
"    add $16, %rsp\n"
"    pop %r11\n"
"    mov $1, %rax\n"
"    ret\n"
);

